### ISSUE TITLE
Cannot load crashlog from Rails initializer

### ISSUE THREAD

**Issue by pda** [crashlog/crashlog#7]
I configure Rails apps to use `Bundler.setup` instead of `Bundler.require` and then load gems on demand, for much faster Rails startup time.

I've got `crashlog` in my Gemfile, and a `config/initializers/crashlog.rb` which begins with `require "crashlog"`.

That line causes this error:

```
NoMethodError: undefined method `configure' for CrashLog:Module
```

Moving the `require "crashlog"` to just after Bundler setup in `config/application.rb` resolves the problem, but is not ideal - the library should be loadable from a Rails initializer.

I gather the problem is related to how/when CrashLog interacts with Rails / railties.

Cheers,
Paul
## 

```
GEMS/crashlog-1.0.3/lib/crash_log/railtie.rb:12:in `block in <class:Railtie>': undefined method `configure' for CrashLog:Module (NoMethodError)
    from GEMS/activesupport-3.2.8/lib/active_support/lazy_load_hooks.rb:34:in `call'
    from GEMS/activesupport-3.2.8/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
    from GEMS/activesupport-3.2.8/lib/active_support/lazy_load_hooks.rb:26:in `block in on_load'
    from GEMS/activesupport-3.2.8/lib/active_support/lazy_load_hooks.rb:25:in `each'
    from GEMS/activesupport-3.2.8/lib/active_support/lazy_load_hooks.rb:25:in `on_load'
    from GEMS/railties-3.2.8/lib/rails/railtie/configuration.rb:54:in `before_initialize'
    from GEMS/crashlog-1.0.3/lib/crash_log/railtie.rb:11:in `<class:Railtie>'
    from GEMS/crashlog-1.0.3/lib/crash_log/railtie.rb:6:in `<module:CrashLog>'
    from GEMS/crashlog-1.0.3/lib/crash_log/railtie.rb:5:in `<top (required)>'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
    from GEMS/crashlog-1.0.3/lib/crash_log.rb:16:in `<top (required)>'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
    from GEMS/crashlog-1.0.3/lib/crashlog.rb:1:in `<top (required)>'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `block in require'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:251:in `require'
    from APP/config/initializers/crashlog.rb:3:in `<top (required)>'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in `load'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in `block in load'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:236:in `load_dependency'
    from GEMS/activesupport-3.2.8/lib/active_support/dependencies.rb:245:in `load'
    from GEMS/railties-3.2.8/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
    from GEMS/railties-3.2.8/lib/rails/engine.rb:587:in `each'
    from GEMS/railties-3.2.8/lib/rails/engine.rb:587:in `block in <class:Engine>'
    from GEMS/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
    from GEMS/railties-3.2.8/lib/rails/initializable.rb:30:in `run'
    from GEMS/railties-3.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
    from GEMS/railties-3.2.8/lib/rails/initializable.rb:54:in `each'
    from GEMS/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
    from GEMS/railties-3.2.8/lib/rails/application.rb:136:in `initialize!'
    from GEMS/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from APP/config/environment.rb:5:in `<top (required)>'
    from ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from APP/spec/spec_helper_full.rb:3:in `<top (required)>'
    from APP/spec/spec_helper.rb:3:in `require_relative'
    from APP/spec/spec_helper.rb:3:in `<top (required)>'
    from ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from APP/spec/api/conversation_authorization_api_spec.rb:1:in `<top (required)>'
    from GEMS/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load'
    from GEMS/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `block in load_spec_files'
    from GEMS/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `map'
    from GEMS/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load_spec_files'
    from GEMS/rspec-core-2.11.1/lib/rspec/core/command_line.rb:22:in `run'
    from GEMS/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
    from GEMS/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
```

**Comment by ivanvanderbyl** [comment]
What's your setup rails version/ruby version ?

Regards,
Ivan Vanderbyl

**Comment by pda** [comment]
```
Rails 3.2.8
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.2.0]
Darwin paulbookpro.lan 12.2.0 Darwin Kernel Version 12.2.0: Sat Aug 25 00:48:52 PDT 2012; root:xnu-2050.18.24~1/RELEASE_X86_64 x86_64
```

**Comment by ivanvanderbyl** [comment]
Excellent, I've replicated this locally and have a pretty good idea of the fix. I'm about to jump on a flight back to Melbourne — hopefully get it fixed in the air.

**Comment by ivanvanderbyl** [comment]
@pda I think I've fixed it, can you point bundler to:

``` ruby
gem "crashlog", git: "git://github.com/crashlog/crashlog.git"
```

And test it out. If it all looks good I'll release 1.0.4

**Comment by ivanvanderbyl** [comment]
OK so as it turns out, Bundler treats gems loaded with `:path` and `:git` differently. So this actually didn't fix it.

Basically what is happening is, we're loading the railtie before loading the CrashLog module itself, which means ruby treats it as loaded even though it hasn't been eval'd by the time we call configure.

**Comment by pda** [comment]
Unfortunately that doesn't fix it, regardless of `:git` or `:path`.

Your `lib/crash_log.rb` has this line prior to the definition of `CrashLog.configure`:

``` ruby
require_relative 'crash_log/railtie' if defined?(Rails::Railtie)
```

That line triggers the ActiveSupport hooks inline rather than deferring them to later, I guess because Rails is already loaded/loading. They try to refer to `CrashLog.configure` which isn't defined yet.

Moving that `require_relative` to the end of `lib/crash_log.rb` fixes it, but isn't pretty.

Pulling the configuration into a separate file which could be loaded prior to `crash_log/railtie` would be an option.

**Comment by ivanvanderbyl** [comment]
Looks like we both came to the same conclusion. I think moving the railtie require to the end is fine for now, I might refactor this in the coming weeks.

**Comment by pda** [comment]
One possible refactor would be creating a `crashlog-rails` gem, and extracting anything Rails-specific into there.
Then normal gem dependency resolution would resolve the load order problem.

**Comment by pda** [comment]
(One day, maybe, when there's time) :wink:

**Comment by ivanvanderbyl** [comment]
Yeah that would be a nice idea. Although I also believe the CrashLog module is getting rather bloated.

**Comment by ivanvanderbyl** [comment]
OK it should be resolved on master, I've tested it against Rails 3.2.6/Ruby 1.9.3-p194 doing both `Bundler.setup` and `Bundler.require`

**Comment by pda** [comment]
Bam — works for me against latest commit 5ce2cb2fea5b3ed2c6671c2ec3be4cedbee7e75b.
Thanks Ivan!

**Comment by ivanvanderbyl** [comment]
Awesome!

I've just got a bunch of tests to fix and params filtering to sort out until I re-enable the request payload (Full of lots of things that break JSON encoding) and push out 1.0.4 — hopefully today.

If you have any more issues post them here and I'll get them sorted out.
